#' Data Summary
#'
#' Uses the data frame generated by the readnames function and creates
#' graphics associated with the data
#'
#'
#' @examples
#'
#'
#' @import ggplot2
#' @export

datasummary <- function(type){

  library(ggplot2)
  ##Pulls from the totaldata function so that the dataset can be initialized here
  source("~/names/R/totaldata.R")
  dat <- totaldata()

  ##Creates a summary of the data that are useful for the type of analysis
  count <- table(unlist(dat))
  num <- cbind(c(summary(dat$year),
                 summary(dat$major),
                 summary(dat$honors),
                 summary(dat$degree),
                 summary(dat$ethnicity)))

  ##Creates a dataframe of the counts of data
  if (type == "count"){
    num
  }

  else if (type == "timeline"){
    ##Creates a timeline of the proportion of jewish summa, magna, and cummas
    ##out of jewish people

    ##Reformatting the datamatrix to make plotting easier

    ##this table creates the frequency of jews, not proportions
    jew <- data.frame(table(dat$Jewstatus, dat$year, dat$degree))
    colnames(jew) <- c("jewstatus", "year", "degree", "freq")

    ##Creating the proportions of summa per year matrix

    ##Creating the proportions of magna per year matrix

    ##Creating the proportions of cum per year matrix

    ##Creating the proportions of Jewish people at Williams per year matrix

    ##Puts everything together into a plot
    ggplot(data=jew, aes(x = year, y = freq, group = degree,  col= degree)) + geom_point() + geom_line()
  }


}
